[project]
name = "transcription-correction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lowestofthe1ow", email = "1owestoftheow@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
transcription-correction = "transcription_correction:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
